name: Des W Woodruff
favicon: null
layout_spectrum: 0.1570300436578691
typography_spectrum: 0.2582414518110454
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6328004880342633
  lightness: 0.25775527814403176
  saturation: 0.47044946951791644
  rhythmicContrast: 0.7521395056974143
purpose: []
